# Image of workspace. Learn more: https://www.gitpod.io/docs/configure/workspaces/workspace-image
image: gitpod/workspace-full:latest
vscode:
  extensions:
    - "esbenp.prettier-vscode"

# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - init: npm i -g turbo prettier && pnpm i --frozen-lockfile # runs during prebuild => https://www.gitpod.io/docs/configure/projects/prebuilds

