# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  # runs during prebuild => https://www.gitpod.io/docs/configure/projects/prebuilds
  - init: |
      npm i -g vercel
      pnpm i --frozen-lockfile
