# Image of workspace. Learn more: https://www.gitpod.io/docs/configure/workspaces/workspace-image
image:
  file: .gitpod.Dockerfile

# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  # runs during prebuild => https://www.gitpod.io/docs/configure/projects/prebuilds
  - init: pnpm i --frozen-lockfile
