[dev]
  framework = "astro"
  autoLaunch = false

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"

[[headers]]
  for = "/_astro/*"
  [headers.values]
    cache-control = '''
    max-age=31536000,
    immutable
    '''

[[headers]]
  for = "/uploads/*"
  [headers.values]
    cache-control = '''
    max-age=31536000,
    immutable
    '''

# Config for the Netlify Build Plugin: netlify-plugin-minify-html
[[plugins]]
  package = "netlify-plugin-minify-html"

  # Optionally, override the default options for the minification
  # https://github.com/kangax/html-minifier#options-quick-reference
  [plugins.inputs.minifierOptions]
    collapseWhitespace = true
    conservativeCollapse = true
    minifyCSS = true
    minifyJS = true
    minifyURLs = true
    removeComments = true