title: blog.sngr.my.id
description: >-
  Pemuda dari Sampit, Kalimantan Tengah. Sehari-hari bergaul dengan komputer,
  namun tetap berusaha aktif sebagai warga.
logo: ~/assets/site/logo.jpg
menu:
  - name: Tentang
    slug: tentang
  - name: Catatan
    slug: notes
  - name: Series
    slug: series
  - name: Karya
    slug: karya
