title: radenpioneer.blog
description: orang biasa, seperti kamu. iya, kamu...
image: ~/assets/profile.jpg
menu:
  - title: siapa?
    href: /siapa
  - title: catatan
    href: /note
  - title: karya
    href: /karya
