title: radenpioneer.blog
description: orang biasa, seperti kamu. iya, kamu.
image: /src/assets/uploads/site/image.jpg
menu:
  - name: Siapa?
    slug: siapa
  - name: Esai
    slug: esai
  - name: Catatan
    slug: tags/catatan-mingguan
